### ISSUE TITLE
Exit code 2 when BRANCH_ALIASES is not defined

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/deploy-book-workflow#6]
This gave an exit code 2: https://github.com/TeachBooks/Quick_Reference/actions/runs/8733086952 at that moment BRANCH_ALIASES was not defined
This run succeeded: https://github.com/TeachBooks/Quick_Reference/actions/runs/8733106355 the only thing I changed what defining BRANCH_ALIASES as <space>

**Comment by severinbratus** [comment]
The issue is that the default value of `BRANCH_ALIASES` (which is set if undefined) is `draft:main`, and `draft` is also a branch in the repo -- hence a conflict.

I see multiple things we could do (non-exclusive):
1. No aliases by default.
2. Error message to notify the users the alias name cannot conflict with an existing branch.

**Comment by Tom-van-Woudenberg** [comment]
Both would be nice. Would there be other cases which would cause unclear errors for which we can provide a more specific error message?
- naming nog existing branch 
- invalid syntax
- same alias
